CREATE TABLE "WorkflowInstances" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    status integer NOT NULL,
    workflow_name text NOT NULL,
    workflow_version integer NOT NULL,
    data jsonb,
    CONSTRAINT "PK_WorkflowInstances" PRIMARY KEY (id)
);


CREATE TABLE "WorkflowExecutionPoints" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    step_id text NOT NULL,
    activity_type text NOT NULL,
    status integer NOT NULL,
    workflow_instance_id integer NOT NULL,
    CONSTRAINT "PK_WorkflowExecutionPoints" PRIMARY KEY (id),
    CONSTRAINT "FK_WorkflowExecutionPoints_WorkflowInstances_workflow_instance~" FOREIGN KEY (workflow_instance_id) REFERENCES "WorkflowInstances" (id) ON DELETE CASCADE
);


CREATE TABLE "WorkflowBookmarks" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    status integer NOT NULL,
    workflow_execution_point_id integer NOT NULL,
    CONSTRAINT "PK_WorkflowBookmarks" PRIMARY KEY (id),
    CONSTRAINT "FK_WorkflowBookmarks_WorkflowExecutionPoints_workflow_executio~" FOREIGN KEY (workflow_execution_point_id) REFERENCES "WorkflowExecutionPoints" (id) ON DELETE CASCADE
);


CREATE TABLE "UserTasks" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    display_name text NOT NULL,
    workflow_bookmark_id integer NOT NULL,
    CONSTRAINT "PK_UserTasks" PRIMARY KEY (id),
    CONSTRAINT "FK_UserTasks_WorkflowBookmarks_workflow_bookmark_id" FOREIGN KEY (workflow_bookmark_id) REFERENCES "WorkflowBookmarks" (id) ON DELETE CASCADE
);


CREATE INDEX "IX_UserTasks_workflow_bookmark_id" ON "UserTasks" (workflow_bookmark_id);


CREATE UNIQUE INDEX "IX_WorkflowBookmarks_workflow_execution_point_id" ON "WorkflowBookmarks" (workflow_execution_point_id);


CREATE INDEX "IX_WorkflowExecutionPoints_workflow_instance_id" ON "WorkflowExecutionPoints" (workflow_instance_id);


