// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WorkflowProcessor.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20250317134838_WorkflowInstanceParent")]
    partial class WorkflowInstanceParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<int>("WorkflowExecutionPointId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_execution_point_id")
                        .HasAnnotation("Relational:JsonPropertyName", "workflowExecutionPointId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionPointId")
                        .IsUnique();

                    b.ToTable("WorkflowBookmarks");
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_id")
                        .HasAnnotation("Relational:JsonPropertyName", "activityId");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type")
                        .HasAnnotation("Relational:JsonPropertyName", "activityType");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_instance_id")
                        .HasAnnotation("Relational:JsonPropertyName", "workflowInstanceId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowExecutionPoints");

                    b.HasAnnotation("Relational:JsonPropertyName", "workflowExecutionPoint");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "parent_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("WorkflowInstances");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");
                });

            modelBuilder.Entity("WorkflowBookmark", b =>
                {
                    b.HasOne("WorkflowExecutionPoint", "WorkflowExecutionPoint")
                        .WithOne("WorkflowBookmark")
                        .HasForeignKey("WorkflowBookmark", "WorkflowExecutionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecutionPoint");
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.HasOne("WorkflowProcessor.Core.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowExecutionPoints")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.HasOne("WorkflowProcessor.Core.WorkflowInstance", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("parent_children_fk");

                    b.OwnsOne("WorkflowProcessor.Core.WorkflowInfo", "WorkflowInfo", b1 =>
                        {
                            b1.Property<int>("WorkflowInstanceId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("workflow_name")
                                .HasAnnotation("Relational:JsonPropertyName", "name");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("workflow_version")
                                .HasAnnotation("Relational:JsonPropertyName", "version");

                            b1.HasKey("WorkflowInstanceId");

                            b1.ToTable("WorkflowInstances");

                            b1.HasAnnotation("Relational:JsonPropertyName", "workflowInfo");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowInstanceId");
                        });

                    b.OwnsOne("WorkflowProcessor.Persistance.Context.Context", "Context", b1 =>
                        {
                            b1.Property<int>("WorkflowInstanceId")
                                .HasColumnType("integer");

                            b1.Property<string>("JsonData")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("data");

                            b1.HasKey("WorkflowInstanceId");

                            b1.ToTable("WorkflowInstances");

                            b1.HasAnnotation("Relational:JsonPropertyName", "context");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowInstanceId");
                        });

                    b.Navigation("Context")
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("WorkflowInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.Navigation("WorkflowBookmark");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("WorkflowExecutionPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
