// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WorkflowProcessor.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20250310143417_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkflowExecutionPointId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_execution_point_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionPointId")
                        .IsUnique();

                    b.ToTable("WorkflowBookmarks");
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowExecutionPoints");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonData")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("WorkflowBookmark", b =>
                {
                    b.HasOne("WorkflowExecutionPoint", "WorkflowExecutionPoint")
                        .WithOne("WorkflowBookmark")
                        .HasForeignKey("WorkflowBookmark", "WorkflowExecutionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecutionPoint");
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.HasOne("WorkflowProcessor.Core.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowExecutionPoints")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.OwnsOne("WorkflowProcessor.Core.Workflow", "Workflow", b1 =>
                        {
                            b1.Property<int>("WorkflowInstanceId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("workflow_name");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("workflow_version");

                            b1.HasKey("WorkflowInstanceId");

                            b1.ToTable("WorkflowInstances");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowInstanceId");
                        });

                    b.Navigation("Workflow")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowExecutionPoint", b =>
                {
                    b.Navigation("WorkflowBookmark");
                });

            modelBuilder.Entity("WorkflowProcessor.Core.WorkflowInstance", b =>
                {
                    b.Navigation("WorkflowExecutionPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
