<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<PackAsTool>true</PackAsTool>
	<ToolCommandName>wfp-tool</ToolCommandName>
	<PackageOutputPath>./nupkg</PackageOutputPath>
	<OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version>1.0.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="18.0.2" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkflowProcessor\WorkflowProcessor.csproj" />
  </ItemGroup>

</Project>
